<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/04/13 07:10:59
sfConfig::add(array(
  'app_organization' => 'Karlovy Vary',
  'app_crontab_folder' => '/home/mirek/cron/',
  'app_knowledgetree_root' => '/home/mirek/knowledgetree/',
  'app_sf_guard_plugin_signin_form' => 'LoginForm',
  'app_max_reports_on_page' => 5,
));
