<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/03/08 09:48:46

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:host=localhost;dbname=project',
  'username' => 'root',
  'password' => 'heavyboys',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
