# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
 organization: Karlovy Vary
 crontab:
  folder: /home/mirek/cron/
 knowledgetree:
  root: /home/mirek/knowledgetree/
 sf_guard_plugin:
  signin_form:    LoginForm

