<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2011/03/10 00:27:08
return array(

  // sfPropelPlugin_module_libs

  // sfPropelPlugin_lib
  'sfpropeldatabase' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/database/sfPropelDatabase.class.php',
  'sftesterpropel' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/test/sfTesterPropel.class.php',
  'sfformfilterpropel' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/form/sfFormFilterPropel.class.php',
  'sfformpropel' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/form/sfFormPropel.class.php',
  'sfpropelbehaviori18n' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18n.php',
  'sfpropelbehaviorbase' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorBase.php',
  'sfpropelbehaviorsymfony' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfony.php',
  'sfpropelbehaviorsymfonybehaviors' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorSymfonyBehaviors.php',
  'sfpropelbehaviori18ntranslation' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorI18nTranslation.php',
  'sfpropelbehaviortimestampable' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/behavior/SfPropelBehaviorTimestampable.php',
  'sfpropeldatadumptask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelDataDumpTask.class.php',
  'sfpropelbuildallloadtask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllLoadTask.class.php',
  'sfpropelbasetask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBaseTask.class.php',
  'sfpropelgraphviztask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelGraphvizTask.class.php',
  'sfpropelbuildtask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildTask.class.php',
  'sfpropeldataloadtask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelDataLoadTask.class.php',
  'sfpropelbuildsqltask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildSqlTask.class.php',
  'sfpropelschematoxmltask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToXmlTask.class.php',
  'sfpropelconfiguredatabasetask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelConfigureDatabaseTask.class.php',
  'sfphinglistener' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPhingListener.php',
  'sfpropelbuildfilterstask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildFiltersTask.class.php',
  'sfpropelbuildalltask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildAllTask.class.php',
  'sfpropelgeneratemoduleforroutetask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleForRouteTask.class.php',
  'sfpropelgenerateadmintask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelGenerateAdminTask.class.php',
  'sfpropelgeneratemoduletask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelGenerateModuleTask.class.php',
  'sfpropelbuildschematask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildSchemaTask.class.php',
  'sfpropelinsertsqltask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelInsertSqlTask.class.php',
  'sfpropelschematoymltask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelSchemaToYmlTask.class.php',
  'sfpropelbuildmodeltask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildModelTask.class.php',
  'sfphing' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPhing.class.php',
  'sfpropelbuildformstask' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/task/sfPropelBuildFormsTask.class.php',
  'sfpropellogger' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/log/sfPropelLogger.class.php',
  'sfwebdebugpanelpropel' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/debug/sfWebDebugPanelPropel.class.php',
  'swift_propelspool' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/mailer/Swift_PropelSpool.class.php',
  'sfpropelroute' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/routing/sfPropelRoute.class.php',
  'sfpropelroutecollection' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/routing/sfPropelRouteCollection.class.php',
  'sfwidgetformpropelchoice' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/widget/sfWidgetFormPropelChoice.class.php',
  'sfpropelpager' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/addon/sfPropelPager.class.php',
  'sfpropeldata' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/addon/sfPropelData.class.php',
  'sfmixer' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/addon/sfMixer.class.php',
  'sfpropel' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/addon/sfPropel.class.php',
  'sfpropelbehavior' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/addon/sfPropelBehavior.class.php',
  'sfpropelmanytomany' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/addon/sfPropelManyToMany.class.php',
  'sfpropeldatabaseschema' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/addon/sfPropelDatabaseSchema.class.php',
  'sfvalidatorpropelchoice' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelChoice.class.php',
  'sfvalidatorpropelunique' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/validator/sfValidatorPropelUnique.class.php',
  'sfpropelformfiltergenerator' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/generator/sfPropelFormFilterGenerator.class.php',
  'sfpropelformgenerator' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/generator/sfPropelFormGenerator.class.php',
  'sfpropelgenerator' => '/usr/share/php/symfony/plugins/sfPropelPlugin/lib/generator/sfPropelGenerator.class.php',

  // project
  'carform' => '/var/www/project/lib/form/CarForm.class.php',
  'reportform' => '/var/www/project/lib/form/ReportForm.class.php',
  'basecarform' => '/var/www/project/lib/form/base/BaseCarForm.class.php',
  'basereportform' => '/var/www/project/lib/form/base/BaseReportForm.class.php',
  'baseformpropel' => '/var/www/project/lib/form/BaseFormPropel.class.php',
  'baseform' => '/var/www/project/lib/form/BaseForm.class.php',
  'crontabform' => '/var/www/project/lib/form/CrontabForm.class.php',
  'baseformfilterpropel' => '/var/www/project/lib/filter/BaseFormFilterPropel.class.php',
  'basecarformfilter' => '/var/www/project/lib/filter/base/BaseCarFormFilter.class.php',
  'basereportformfilter' => '/var/www/project/lib/filter/base/BaseReportFormFilter.class.php',
  'carformfilter' => '/var/www/project/lib/filter/CarFormFilter.class.php',
  'reportformfilter' => '/var/www/project/lib/filter/ReportFormFilter.class.php',

  // project_model
  'cartablemap' => '/var/www/project/lib/model/map/CarTableMap.php',
  'reporttablemap' => '/var/www/project/lib/model/map/ReportTableMap.php',
  'report' => '/var/www/project/lib/model/Report.php',
  'reportpeer' => '/var/www/project/lib/model/ReportPeer.php',
  'basereport' => '/var/www/project/lib/model/om/BaseReport.php',
  'basereportpeer' => '/var/www/project/lib/model/om/BaseReportPeer.php',
  'basecarpeer' => '/var/www/project/lib/model/om/BaseCarPeer.php',
  'basecar' => '/var/www/project/lib/model/om/BaseCar.php',
  'car' => '/var/www/project/lib/model/Car.php',
  'carpeer' => '/var/www/project/lib/model/CarPeer.php',

  // application
  'myuser' => '/var/www/project/apps/frontend/lib/myUser.class.php',

  // modules
);
