<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/03/09 23:31:40
sfConfig::add(array(
  'app_organization' => 'Karlovy Vary',
  'app_crontab_folder' => '/home/mirek/cron/',
  'app_knowledgetree_root' => '/home/mirek/knowledgetree/',
));
